

trigger:
- main
stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: server1
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/target/'
        Contents: 'netflix.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
