trigger:
- main

pool:
  name: dev-pool

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/target/'
    Contents: 'netflix.war'
    targetFolder: '$(Build.ArtifactStagingDirectory)/'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

